/**
 * Count words from string input, return
 * @param {String} str - The input string
 * @return {number} - The number of words
 */
const countWords = (str) => {
	str = str.trim().replace(/(^\s*)|(\s*$)/gi, "");
	str = str.replace(/[ ]{2,}/gi, " ");
	str = str.replace(/\n /, "\n");
	return str.split(" ").length;
};

/**
 * Get cookie value
 * @param {String} name - The name of desired cookie
 * @return {String} - The value of the cookie
 */
export const getCookie = (name) => {
	let cookieValue = null;
	if (document.cookie && document.cookie !== "") {
		const cookies = document.cookie.split(";");
		for (let i = 0; i < cookies.length; i++) {
			const cookie = cookies[i].trim();
			// Does this cookie string begin with the name we want?
			if (cookie.substring(0, name.length + 1) === name + "=") {
				cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
				break;
			}
		}
	}
	return cookieValue;
};

/**
 * Wrapper of fetch to be used with crsf token, generated by django
 * @param {String} url - Target URL
 * @return {JSON} - Requset params
 */
const djangoCall = async (url = "", data = {}, method = "POST") => {
	// Default options are marked with *
	let options = {
		method: method,
	};
	if (method != "GET" && method != "HEAD") options["body"] = JSON.stringify(data);

	if ((method = "POST")) {
		options.mode = "cors";
		options.headers = {
			"X-CSRFToken": document.querySelector("[name=csrfmiddlewaretoken]").value,
		};
	}
	const response = await fetch(url, options);
	if (response.ok) {
		return response.json();
	} else {
		throw new Error("Something went wrong ...");
	}
};

/**
 * Generate random hex color code.
 * @void
 **/
const randomColor = () => "#" + (Math.random() * 0xfffff * 1000000).toString(16).slice(0, 6);

/**
 * Take start and end number to generate a list in that range
 * @param {number} start - Start number
 * @param {number} end - End number
 * @returns {Arrray}
 */
const range = (start, end) => {
	return Array.apply(0, Array(end - 1)).map((_, index) => index + start);
};

export default { countWords, getCookie, randomColor, range, djangoCall };
